export const menu = [
  {
    id: 1,
    title: "main",
    menulist: [
      {
        id: 1,
        url: "/",
        listTitle: "homepage",
        icon: "home.svg",
      },
      {
        id: 2,
        url: "/user/1",
        listTitle: "profile",
        icon: "user.svg",
      },
    ],
  },
  {
    id: 2,
    title: "lists",
    menulist: [
      {
        id: 1,
        url: "/users",
        listTitle: "users",
        icon: "user.svg",
      },
      {
        id: 2,
        url: "/products",
        listTitle: "products",
        icon: "product.svg",
      },
      {
        id: 3,
        url: "/orders",
        listTitle: "orders",
        icon: "order.svg",
      },
      {
        id: 4,
        url: "/posts",
        listTitle: "posts",
        icon: "post.svg",
      },
    ],
  },
  {
    id: 3,
    title: "general",
    menulist: [
      {
        id: 1,
        url: "/",
        listTitle: "elements",
        icon: "element.svg",
      },
      {
        id: 2,
        url: "/",
        listTitle: "notes",
        icon: "note.svg",
      },
      {
        id: 3,
        url: "/",
        listTitle: "forms",
        icon: "form.svg",
      },
      {
        id: 4,
        url: "/",
        listTitle: "calendar",
        icon: "calendar.svg",
      },
    ],
  },
  {
    id: 4,
    title: "maintenance",
    menulist: [
      {
        id: 1,
        url: "/",
        listTitle: "settings",
        icon: "setting.svg",
      },
      {
        id: 2,
        url: "/",
        listTitle: "backups",
        icon: "backup.svg",
      },
    ],
  },
  {
    id: 5,
    title: "analytics",
    menulist: [
      {
        id: 1,
        url: "/",
        listTitle: "charts",
        icon: "chart.svg",
      },
      {
        id: 2,
        url: "/",
        listTitle: "logs",
        icon: "log.svg",
      },
    ],
  },
];

export const topdeals = [
  {
    id: 1,
    name: "John Barasa",
    email: "johnb@gmail.com",
    amount: "24,000",
    photo:
      "https://images.pexels.com/photos/1559486/pexels-photo-1559486.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
  },
  {
    id: 2,
    name: "Peris Nasibo",
    email: "nasibo@gmail.com",
    amount: "89,000",
    photo:
      "https://images.pexels.com/photos/1449667/pexels-photo-1449667.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
  },
  {
    id: 3,
    name: "Jully Njeri",
    email: "njully34@gmail.com",
    amount: "51,000",
    photo:
      "https://images.pexels.com/photos/2013701/pexels-photo-2013701.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
  },
  {
    id: 4,
    name: "Pius Ochieng'",
    email: "ochiep@gmail.com",
    amount: "16,000",
    photo:
      "https://images.pexels.com/photos/4277088/pexels-photo-4277088.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 5,
    name: "Willy Kuzma",
    email: "kuzwi@gmail.com",
    amount: "102,000",
    photo:
      "https://images.pexels.com/photos/4586688/pexels-photo-4586688.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 6,
    name: "Clare Travis",
    email: "clare@gmail.com",
    amount: "92,000",
    photo:
      "https://images.pexels.com/photos/3290250/pexels-photo-3290250.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
];

export const chartBoxUser = {
  color: "#8884d8",
  icon: "/userIcon.svg",
  title: "Total Users",
  number: "1,238",
  dataKey: "users",
  percentage: 45,
  chartData: [
    { name: "Sun", users: 400 },
    { name: "Mon", users: 600 },
    { name: "Tue", users: 500 },
    { name: "Wed", users: 700 },
    { name: "Thu", users: 400 },
    { name: "Fri", users: 500 },
    { name: "Sat", users: 450 },
  ],
};

export const chartBoxRevenue = {
  color: "teal",
  icon: "/revenueIcon.svg",
  title: "Total Revenues",
  number: "Ksh.6376",
  dataKey: "revenue",
  percentage: -12,
  chartData: [
    { name: "Sun", revenue: 400 },
    { name: "Mon", revenue: 600 },
    { name: "Tue", revenue: 500 },
    { name: "Wed", revenue: 700 },
    { name: "Thu", revenue: 400 },
    { name: "Fri", revenue: 500 },
    { name: "Sat", revenue: 450 },
  ],
};

export const chartBoxConversion = {
  color: "gold",
  icon: "/conversionIcon.svg",
  title: "Total Ratio",
  number: "2.9",
  dataKey: "ratio",
  percentage: 15,
  chartData: [
    { name: "Sun", ratio: 400 },
    { name: "Mon", ratio: 600 },
    { name: "Tue", ratio: 500 },
    { name: "Wed", ratio: 700 },
    { name: "Thu", ratio: 400 },
    { name: "Fri", ratio: 500 },
    { name: "Sat", ratio: 450 },
  ],
};

export const chartBoxProduct = {
  color: "skyblue",
  icon: "/productIcon.svg",
  title: "Total Products",
  number: "309",
  dataKey: "products",
  percentage: 32,
  chartData: [
    { name: "Sun", products: 400 },
    { name: "Mon", products: 600 },
    { name: "Tue", products: 500 },
    { name: "Wed", products: 700 },
    { name: "Thu", products: 400 },
    { name: "Fri", products: 500 },
    { name: "Sat", products: 450 },
  ],
};

export const barChart1 = {
  title: "Profit Earned",
  color: "#8884d8",
  dataKey: "profit",
  chartData: [
    { name: "Sun", profit: 4000 },
    { name: "Mon", profit: 3000 },
    { name: "Tue", profit: 2000 },
    { name: "Wed", profit: 2780 },
    { name: "Thu", profit: 1890 },
    { name: "Fri", profit: 2390 },
    { name: "Sat", profit: 3490 },
  ],
};

export const barChart2 = {
  title: "Total Visits",
  color: "#FF8042",
  dataKey: "visit",
  chartData: [
    { name: "Sun", visit: 4000 },
    { name: "Mon", visit: 3000 },
    { name: "Tue", visit: 2000 },
    { name: "Wed", visit: 2780 },
    { name: "Thu", visit: 1890 },
    { name: "Fri", visit: 2390 },
    { name: "Sat", visit: 3490 },
  ],
};

export const rows = [
  {
    id: 1,
    img: "https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=600",
    lastName: "Hubbard",
    firstName: "Eula",
    email: "kez@gmail.com",
    phone: "0123 769 564",
    createdAt: "01.02.2023",
    verified: true,
  },
  {
    id: 2,
    img: "https://images.pexels.com/photos/712413/pexels-photo-712413.jpeg?auto=compress&cs=tinysrgb&w=600",
    lastName: "Nyanchera",
    firstName: "Diana",
    email: "nyax@gmail.com",
    phone: "0132 766 405",
    createdAt: "01.02.2023",
    verified: false,
  },
  {
    id: 3,
    img: "https://images.pexels.com/photos/4126784/pexels-photo-4126784.jpeg?auto=compress&cs=tinysrgb&w=600",
    lastName: "Achola",
    firstName: "Nereah",
    email: "achix@gmail.com",
    phone: "0112 564 876",
    createdAt: "11.03.2023",
    verified: false,
  },
  {
    id: 4,
    img: "https://images.pexels.com/photos/2641773/pexels-photo-2641773.jpeg?auto=compress&cs=tinysrgb&w=600",
    lastName: "Bwire",
    firstName: "Colins",
    email: "bwix@gmail.com",
    phone: "0769 564 675",
    createdAt: "01.05.2023",
    verified: true,
  },
  {
    id: 5,
    img: "https://images.pexels.com/photos/4946413/pexels-photo-4946413.jpeg?auto=compress&cs=tinysrgb&w=600",
    lastName: "Muema",
    firstName: "Justine",
    email: "mj@gmail.com",
    phone: "0110 749 564",
    createdAt: "01.02.2023",
    verified: false,
  },
  {
    id: 6,
    img: "https://images.pexels.com/photos/4586688/pexels-photo-4586688.jpeg?auto=compress&cs=tinysrgb&w=600",
    lastName: "Kianjokoma",
    firstName: "Chris",
    email: "njoks@gmail.com",
    phone: "0793 769 564",
    createdAt: "01.02.2023",
    verified: true,
  },
  {
    id: 7,
    img: "https://images.pexels.com/photos/3881172/pexels-photo-3881172.jpeg?auto=compress&cs=tinysrgb&w=600",
    lastName: "Karembo",
    firstName: "Caro",
    email: "kac@gmail.com",
    phone: "0713 609 560",
    createdAt: "15.04.2023",
    verified: true,
  },
  {
    id: 8,
    img: "https://images.pexels.com/photos/6939060/pexels-photo-6939060.jpeg?auto=compress&cs=tinysrgb&w=600",
    lastName: "Kilungi",
    firstName: "Musula",
    email: "kilm@gmail.com",
    phone: "0732 769 564",
    createdAt: "01.10.2023",
    verified: true,
  },
  {
    id: 9,
    img: "https://images.pexels.com/photos/5721335/pexels-photo-5721335.jpeg?auto=compress&cs=tinysrgb&w=600",
    lastName: "Opondo",
    firstName: "Gerrard",
    email: "ger2@gmail.com",
    phone: "0721 976 564",
    createdAt: "30.05.2023",
    verified: false,
  },
  {
    id: 10,
    img: "https://images.pexels.com/photos/5444894/pexels-photo-5444894.jpeg?auto=compress&cs=tinysrgb&w=600",
    lastName: "Nabwire",
    firstName: "Michelle",
    email: "nabz@gmail.com",
    phone: "0734 769 465",
    createdAt: "01.20.2023",
    verified: true,
  },
  {
    id: 11,
    img: "https://images.pexels.com/photos/5506098/pexels-photo-5506098.jpeg?auto=compress&cs=tinysrgb&w=600",
    lastName: "Masakhalia",
    firstName: "Stephen",
    email: "mas@gmail.com",
    phone: "0720 769 564",
    createdAt: "21.03.2023",
    verified: true,
  },
  {
    id: 12,
    img: "https://images.pexels.com/photos/5543536/pexels-photo-5543536.jpeg?auto=compress&cs=tinysrgb&w=600",
    lastName: "Njomo",
    firstName: "Brian",
    email: "njomo@gmail.com",
    phone: "0713 719 564",
    createdAt: "10.03.2023",
    verified: true,
  },
  {
    id: 13,
    img: "https://images.pexels.com/photos/5376880/pexels-photo-5376880.jpeg?auto=compress&cs=tinysrgb&w=600",
    lastName: "Nekesa",
    firstName: "Cynthia",
    email: "nek@gmail.com",
    phone: "0712 769 564",
    createdAt: "05.05.2023",
    verified: true,
  },
  {
    id: 14,
    img: "https://images.pexels.com/photos/5255249/pexels-photo-5255249.jpeg?auto=compress&cs=tinysrgb&w=600",
    lastName: "Njuguna",
    firstName: "Elsey",
    email: "eln@gmail.com",
    phone: "0723 769 564",
    createdAt: "01.02.2023",
    verified: true,
  },
  {
    id: 15,
    img: "https://images.pexels.com/photos/2923156/pexels-photo-2923156.jpeg?auto=compress&cs=tinysrgb&w=600",
    lastName: "Wafula",
    firstName: "Patrick",
    email: "wap@gmail.com",
    phone: "0713 769 564",
    createdAt: "02.02.2023",
    verified: true,
  },
];

export const products = [
  {
    id: 1,
    img: "https://images.pexels.com/photos/10252290/pexels-photo-10252290.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
    title: "Canon EOS 7",
    color: "Black",
    producer: "Canon Inc.",
    price: "Ksh. 57,999",
    createdAt: "14.04.2021",
    inStock: true,
  },
  {
    id: 2,
    img: "https://images.pexels.com/photos/10670329/pexels-photo-10670329.jpeg?auto=compress&cs=tinysrgb&w=600",
    title: "Hungaria Extra Dry",
    color: "White",
    producer: "Torley",
    price: "Ksh. 1,800",
    createdAt: "02.11.2022",
    inStock: true,
  },
  {
    id: 3,
    img: "https://images.pexels.com/photos/459653/pexels-photo-459653.jpeg?auto=compress&cs=tinysrgb&w=600",
    title: "MacBook Pro M2",
    color: "Grey",
    producer: "Apple",
    price: "Ksh. 235,000",
    createdAt: "26.06.2023",
    inStock: false,
  },
  {
    id: 4,
    img: "https://images.pexels.com/photos/18525574/pexels-photo-18525574/free-photo-of-unboxing-iphone-15-pro-max-box-in-natural-titanium-color-mention-zana_qaradaghy-on-instagram-while-use-this-photo-follow-on-instagram-zana_qaradaghy.jpeg?auto=compress&cs=tinysrgb&w=600",
    title: "iPhone 15 Pro",
    color: "Grey",
    producer: "Apple",
    price: "Ksh. 350,000",
    createdAt: "27.11.2023",
    inStock: true,
  },
  {
    id: 5,
    img: "https://brandcart.co.ke/media/catalog/product/cache/original/samsung-galaxy-s23-ultra-5g-512gb-sm-s918bzgqafc.jpg",
    title: "Galaxy S23",
    color: "Green",
    producer: "Samsung",
    price: "Ksh. 197,995",
    createdAt: "01.02.2023",
    inStock: false,
  },
  {
    id: 6,
    img: "https://m.media-amazon.com/images/I/61DIaXyZ2gL._AC_SX425_.jpg",
    title: "SVS SB-1000 Pro",
    color: "White",
    producer: "SVS Sounds",
    price: "Ksh. 104,710",
    createdAt: "05.07.2023",
    inStock: true,
  },
  {
    id: 7,
    img: "https://sollatek.co.ke/wp-content/uploads/2022/10/svs-1-1.jpg",
    title: "SVS2000",
    color: "White",
    producer: "Sollatek",
    price: "Ksh. 14,384",
    createdAt: "12.05.2023",
    inStock: true,
  },
  {
    id: 8,
    img: "https://i5.walmartimages.com/seo/Wilson-NCAA-Street-Shot-Outdoor-Basketball-Official-Size-29-5_e41edc68-d533-445a-8017-9e18bce6d346_1.0d51d0f7eb9c33d54302ac0bbb889dd0.jpeg?odnHeight=640&odnWidth=640&odnBg=FFFFFF",
    title: "Wilson Basketball",
    color: "Orange",
    producer: "The WSG",
    price: "Ksh. 23,818",
    createdAt: "21.06.2022",
    inStock: false,
  },
  {
    id: 9,
    img: "https://ralphchristian.com/cdn/shop/products/TheIntrepidSport-RoseGold-Packshot_a305f067-fc42-4fb7-b739-4a4d4f779d64_1140x1140.png?v=1667314519",
    title: "The Intrepid Sport",
    color: "Rose Gold",
    producer: "Ralph Christian",
    price: "Ksh. 29,806",
    createdAt: "07.03.2023",
    inStock: true,
  },
  {
    id: 10,
    img: "https://www.phoneplacekenya.com/wp-content/uploads/2022/01/Samsung-Galaxy-S22-5G.jpg",
    title: "Galaxy S22",
    color: "Black",
    producer: "Samsung",
    price: "Ksh. 81,500",
    createdAt: "06.10.2023",
    inStock: false,
  },
  {
    id: 11,
    img: "https://contents.mediadecathlon.com/p1708922/k$965db5fa360ce60ee2b6740d88f81f4a/golf-kit-7-clubs-adult-100-right-handed-graphite-size-1.jpg?format=auto&quality=40&f=800x800",
    title: "Adult golf kit",
    color: "Black & White",
    producer: "Inesis golf",
    price: "Ksh. 39,499",
    createdAt: "15.07.2023",
    inStock: true,
  },
  {
    id: 12,
    img: "https://www.premierleague.com/resources/rebrand/v7.130.2/i/nike-ball-hub/index/24.png",
    title: "Nike Flight",
    color: "Orange",
    producer: "Nike",
    price: "Ksh. 30,230",
    createdAt: "01.09.2023",
    inStock: false,
  },
];
